#!/usr/bin/env ruby

running_containers = `docker ps`.split("\n")[1..-1].map{|i| i.split(" ")[0]}

unless running_containers.empty?
  puts "stopping #{running_containers.join(' ')}"
  puts "docker stop #{running_containers.join(' ')}"
  puts `docker stop #{running_containers.join(' ')}`
else
  puts "no running containers to stop"
end

stopped_containers = `docker ps -a`.split("\n")[1..-1].map{|i| i.split(" ")[0]}

unless stopped_containers.empty?
  puts "killing #{stopped_containers.join(' ')}"
  puts "docker rm #{stopped_containers.join(' ')}"
  puts `docker rm #{stopped_containers.join(' ')}`
else
  puts "no stopped containers to rm"
end
