#!/usr/bin/env ruby

name = ARGV[0].gsub("\n", '')

add_remote_origin = ARGV[1] == '-remote_origin'

puts `curl -u 'MainShayne233' https://api.github.com/user/repos -d '{"name":"#{name}"}'`

giturl = "git@github.com:MainShayne233/#{name}.git\n"

if add_remote_origin
  `git remote add origin #{giturl}`
  puts "made remote origin"
end
